/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Dither: typeof import('./src/components/vue-bits/backgrounds/Dither/Dither.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMain: typeof import('element-plus/es')['ElMain']
    GooeyNav: typeof import('./src/components/vue-bits/components/GooeyNav/GooeyNav.vue')['default']
    PixelBlast: typeof import('./src/components/vue-bits/backgrounds/PixelBlast/PixelBlast.vue')['default']
    ShinyText: typeof import('./src/components/vue-bits/text/ShinyText/ShinyText.vue')['default']
  }
}
